package healy;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class CommentDoc extends javax.swing.JFrame {
    private static int idDoc, idProblem;
    Counsel problem = new Counsel();
    
    /**
     * Creates new form CommentDoc
     */
    public CommentDoc(int idDoc, int idProblem) {
        initComponents();
        this.idDoc = idDoc;
        this.idProblem = idProblem;
        Doctor doc = new Doctor();
        System.out.println(idProblem);
        
        System.out.println("problem showing");
        problemGiver.setText(problem.getUsername(idProblem));
        problemTitle.setText(problem.getTitle(idProblem));
        problemText.setText(problem.getProblem(idProblem));
        
        solutionGiver.setText(doc.getUsername(idDoc));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        footer = new javax.swing.JPanel();
        buttonClinic1 = new javax.swing.JButton();
        buttonClinic = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        solutionGiver = new javax.swing.JLabel();
        problemTitle = new javax.swing.JLabel();
        problemGiver = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        solution = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        problemText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        buttonSave1 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(720, 60));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        footer.setBackground(new java.awt.Color(13, 76, 115));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClinic1.setBackground(new java.awt.Color(144, 224, 239));
        buttonClinic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonLogOutDoc.png"))); // NOI18N
        buttonClinic1.setBorder(null);
        buttonClinic1.setBorderPainted(false);
        buttonClinic1.setContentAreaFilled(false);
        buttonClinic1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClinic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClinic1MouseClicked(evt);
            }
        });
        buttonClinic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClinic1ActionPerformed(evt);
            }
        });
        footer.add(buttonClinic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 160, -1));

        buttonClinic.setBackground(new java.awt.Color(144, 224, 239));
        buttonClinic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonClinic-Select.png"))); // NOI18N
        buttonClinic.setBorder(null);
        buttonClinic.setBorderPainted(false);
        buttonClinic.setContentAreaFilled(false);
        buttonClinic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClinic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClinicMouseClicked(evt);
            }
        });
        buttonClinic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClinicActionPerformed(evt);
            }
        });
        footer.add(buttonClinic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 80, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/footerWide.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        footer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, -1));

        getContentPane().add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 400, 120));

        body.setBackground(new java.awt.Color(13, 76, 115));
        body.setAutoscrolls(true);
        body.setPreferredSize(new java.awt.Dimension(400, 500));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solutionGiver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        solutionGiver.setForeground(new java.awt.Color(255, 255, 255));
        solutionGiver.setText("jLabel2");
        body.add(solutionGiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 340, 40));

        problemTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        problemTitle.setForeground(new java.awt.Color(255, 255, 255));
        problemTitle.setText("jLabel2");
        body.add(problemTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 30));

        problemGiver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        problemGiver.setForeground(new java.awt.Color(255, 255, 255));
        problemGiver.setText("jLabel2");
        body.add(problemGiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 280, 40));

        jScrollPane1.setBackground(new java.awt.Color(0, 119, 182));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        solution.setBackground(new java.awt.Color(0, 119, 182));
        solution.setColumns(20);
        solution.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        solution.setForeground(new java.awt.Color(255, 255, 255));
        solution.setRows(5);
        solution.setText("Label panel");
        solution.setBorder(null);
        solution.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(solution);

        body.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 340, 220));

        jScrollPane2.setBackground(new java.awt.Color(0, 119, 182));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        problemText.setEditable(false);
        problemText.setBackground(new java.awt.Color(0, 119, 182));
        problemText.setColumns(20);
        problemText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        problemText.setForeground(new java.awt.Color(255, 255, 255));
        problemText.setRows(5);
        problemText.setText("Label panel");
        problemText.setBorder(null);
        problemText.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(problemText);

        body.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 340, 90));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/backgroundProbFix.png"))); // NOI18N
        body.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 400, 230));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/backgroundSolution.png"))); // NOI18N
        body.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 400, 310));

        buttonBack.setBackground(new java.awt.Color(13, 76, 115));
        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonBack.png"))); // NOI18N
        buttonBack.setBorder(null);
        buttonBack.setBorderPainted(false);
        buttonBack.setContentAreaFilled(false);
        buttonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBackMouseClicked(evt);
            }
        });
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        body.add(buttonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 50));

        buttonSave1.setBackground(new java.awt.Color(13, 76, 115));
        buttonSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonSaveBlue.png"))); // NOI18N
        buttonSave1.setBorder(null);
        buttonSave1.setBorderPainted(false);
        buttonSave1.setContentAreaFilled(false);
        buttonSave1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSave1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSave1MouseClicked(evt);
            }
        });
        buttonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSave1ActionPerformed(evt);
            }
        });
        body.add(buttonSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 120, 50));

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 400, 590));

        header.setBackground(new java.awt.Color(13, 76, 115));
        header.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/healy-logo.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setMaximumSize(new java.awt.Dimension(232, 188));
        jLabel3.setMinimumSize(new java.awt.Dimension(232, 188));
        jLabel3.setPreferredSize(new java.awt.Dimension(232, 188));
        header.add(jLabel3);
        jLabel3.setBounds(200, 10, 200, 120);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/headerClinic.png"))); // NOI18N
        header.add(jLabel5);
        jLabel5.setBounds(0, -10, 190, 140);

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClinic1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClinic1MouseClicked
        Index out = new Index();
        out.show();
        dispose();
    }//GEN-LAST:event_buttonClinic1MouseClicked

    private void buttonClinic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClinic1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClinic1ActionPerformed

    private void buttonClinicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClinicMouseClicked
        MenuDoc menu = new MenuDoc(idDoc);
        menu.show();
        dispose();
    }//GEN-LAST:event_buttonClinicMouseClicked

    private void buttonClinicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClinicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClinicActionPerformed

    private void buttonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonBackMouseClicked
        MenuDoc menu = new MenuDoc(idDoc);
        menu.show();
        dispose();
    }//GEN-LAST:event_buttonBackMouseClicked

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonSave1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSave1MouseClicked
        String answer = solution.getText();
        Diary diary = new Diary();
        int result = problem.update(answer, idDoc, idProblem);
        if(result == 1){
            MenuDoc menu = new MenuDoc(idDoc);
            menu.show();
            dispose();
        }else System.out.println("[DEBUG] ANSWER ERROR");
    }//GEN-LAST:event_buttonSave1MouseClicked

    private void buttonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSave1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommentDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommentDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommentDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommentDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommentDoc(idDoc, idProblem).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonClinic;
    private javax.swing.JButton buttonClinic1;
    private javax.swing.JButton buttonSave1;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel problemGiver;
    private javax.swing.JTextArea problemText;
    private javax.swing.JLabel problemTitle;
    private javax.swing.JTextArea solution;
    private javax.swing.JLabel solutionGiver;
    // End of variables declaration//GEN-END:variables
}
