/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JButton;
import java.awt.Color;
import java.awt.Image;
import java.awt.Font;
import java.awt.image.ImageObserver;

/**
 *
 * @author User
 */
public class DiaryMenuCl extends javax.swing.JFrame{
    private static int id;
    JButton buttonChooseDiary = new JButton();
    
    
    /**
     * Creates new form DiaryMenuCl
     */
    public DiaryMenuCl(int iduser) {
        initComponents();
        
        
        Patient client = new Patient();
        System.out.println(iduser);
        int result = client.getData(iduser);
        this.id = iduser;
        System.out.println(iduser);
        
        JButton[] buttonChooseDiary = new JButton[5];
        panelDiary.setSize(394, 260);
        int i = 1, y = 15;
        
        try {
            String url = "jdbc:mysql://localhost:3306/healyDB?zeroDateTimeBehavior=CONVERT_TO_NULL";
            String user = "root";
            String pass = "pass";

            Connection con = DriverManager.getConnection(url, user, pass);
            System.out.println("[debug]BEFORE CHECKING");
            Statement stmt = con.createStatement();
            String Query = "SELECT * FROM diary WHERE user_id = '" + id + "'";
            ResultSet rs = stmt.executeQuery(Query);
            System.out.println("[debug]AFTER CHECKING");

            while (rs.next()) {
                int diaryId = ((Number)rs.getObject("diary_id")).intValue(); 
                buttonChooseDiary[i] = new JButton();
                buttonChooseDiary[i].setBounds(60, y, 274, 45);
                buttonChooseDiary[i].setBackground(new Color(0, 119, 182));
                buttonChooseDiary[i].setFocusable(false);
                buttonChooseDiary[i].setForeground(Color.WHITE);
                buttonChooseDiary[i].setFont(new Font("Segoe UI", 1, 16));
                buttonChooseDiary[i].setText(rs.getString("diary_title"));
                buttonChooseDiary[i].addActionListener(e -> openDiary(diaryId));
                buttonChooseDiary[i].setVisible(true);
                System.out.println("[debug]diary id:" + diaryId);
                System.out.println("[debug]PRINT" + i);
                System.out.println(rs.getString("diary_title"));

                panelDiary.add(buttonChooseDiary[i]);
                panelDiary.setVisible(true);

                i += 1;
                y += 60;
            }

        } catch (SQLException ex) {
            System.out.println("[debug]ERROR PRINT");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        buttonHome = new javax.swing.JButton();
        buttonDiary = new javax.swing.JButton();
        buttonClinic = new javax.swing.JButton();
        buttonForum = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelDiary = new javax.swing.JPanel();
        buttonNewDiary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(720, 60));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(13, 76, 115));
        jPanel1.setMaximumSize(new java.awt.Dimension(394, 852));
        jPanel1.setMinimumSize(new java.awt.Dimension(394, 852));
        jPanel1.setPreferredSize(new java.awt.Dimension(394, 852));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/diaryGirl.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setMaximumSize(new java.awt.Dimension(394, 852));
        jLabel3.setPreferredSize(new java.awt.Dimension(394, 852));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 400, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/healy-logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 6, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/headerDiary.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setIconTextGap(0);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        footer.setBackground(new java.awt.Color(13, 76, 115));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonHome.setBackground(new java.awt.Color(144, 224, 239));
        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonHome.png"))); // NOI18N
        buttonHome.setBorder(null);
        buttonHome.setBorderPainted(false);
        buttonHome.setContentAreaFilled(false);
        buttonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHomeMouseClicked(evt);
            }
        });
        footer.add(buttonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        buttonDiary.setBackground(new java.awt.Color(144, 224, 239));
        buttonDiary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonDiary-select.png"))); // NOI18N
        buttonDiary.setBorder(null);
        buttonDiary.setBorderPainted(false);
        buttonDiary.setContentAreaFilled(false);
        buttonDiary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDiaryMouseClicked(evt);
            }
        });
        footer.add(buttonDiary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 80, -1));

        buttonClinic.setBackground(new java.awt.Color(144, 224, 239));
        buttonClinic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonClinic.png"))); // NOI18N
        buttonClinic.setBorder(null);
        buttonClinic.setBorderPainted(false);
        buttonClinic.setContentAreaFilled(false);
        buttonClinic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClinic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClinicMouseClicked(evt);
            }
        });
        footer.add(buttonClinic, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 80, -1));

        buttonForum.setBackground(new java.awt.Color(144, 224, 239));
        buttonForum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonForum.png"))); // NOI18N
        buttonForum.setBorder(null);
        buttonForum.setBorderPainted(false);
        buttonForum.setContentAreaFilled(false);
        buttonForum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonForum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonForumMouseClicked(evt);
            }
        });
        footer.add(buttonForum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 80, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/footerWide.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        footer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, -1));

        jPanel1.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 400, 120));

        panelDiary.setBackground(new java.awt.Color(13, 76, 115));
        panelDiary.setPreferredSize(new java.awt.Dimension(394, 260));

        javax.swing.GroupLayout panelDiaryLayout = new javax.swing.GroupLayout(panelDiary);
        panelDiary.setLayout(panelDiaryLayout);
        panelDiaryLayout.setHorizontalGroup(
            panelDiaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        panelDiaryLayout.setVerticalGroup(
            panelDiaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jPanel1.add(panelDiary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 394, 260));

        buttonNewDiary.setBackground(new java.awt.Color(13, 76, 115));
        buttonNewDiary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonNewEntry.png"))); // NOI18N
        buttonNewDiary.setBorder(null);
        buttonNewDiary.setBorderPainted(false);
        buttonNewDiary.setContentAreaFilled(false);
        buttonNewDiary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNewDiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNewDiaryMouseClicked(evt);
            }
        });
        buttonNewDiary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewDiaryActionPerformed(evt);
            }
        });
        jPanel1.add(buttonNewDiary, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, 80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public int checkImage(Image image, ImageObserver observer) {
        return super.checkImage(image, observer); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    
    private void openDiary(int diaryId){
        System.out.println("[debug]diary id:" + diaryId);
        DiaryShowCl diary = new DiaryShowCl(id, diaryId);
        diary.show();
        dispose();
    }
    
    private void buttonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseClicked
        HomeCl homeCl = new HomeCl(id);
        homeCl.show();
        dispose();
    }//GEN-LAST:event_buttonHomeMouseClicked

    private void buttonClinicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClinicMouseClicked
        ClinicMenuCl clinic = new ClinicMenuCl(id);
        clinic.show();
        dispose();
    }//GEN-LAST:event_buttonClinicMouseClicked

    private void buttonForumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonForumMouseClicked
        ForumMenuCl forum = new ForumMenuCl(id);
        forum.show();
        dispose();
    }//GEN-LAST:event_buttonForumMouseClicked

    private void buttonDiaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDiaryMouseClicked
        DiaryMenuCl diaryMenu = new DiaryMenuCl(id);
        diaryMenu.show();
        dispose();
    }//GEN-LAST:event_buttonDiaryMouseClicked

    private void buttonNewDiaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewDiaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNewDiaryActionPerformed

    private void buttonNewDiaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNewDiaryMouseClicked
        DiaryCl diaryEntry = new DiaryCl(id);
        diaryEntry.show();
        dispose();
    }//GEN-LAST:event_buttonNewDiaryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaryMenuCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaryMenuCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaryMenuCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaryMenuCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiaryMenuCl(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClinic;
    private javax.swing.JButton buttonDiary;
    private javax.swing.JButton buttonForum;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonNewDiary;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelDiary;
    // End of variables declaration//GEN-END:variables
}
