/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healy;

/**
 *
 * @author an6el
 */
public class HomeCl extends javax.swing.JFrame {
    private static int id;
    /**
     * Creates new form Diary
     * @param iduser
     */
    public HomeCl(int iduser){
        initComponents();
        this.id = iduser;
        Patient client = new Patient();
        System.out.println(iduser);
        int result = client.getData(iduser);
        
        if(result == 1){
            System.out.println("[DEBUG]Client data imported");
        }else System.out.println("[DEBUG]Client data ERROR");
        
        labelUsername.setText(client.username+"!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonSad = new javax.swing.JButton();
        buttonNeutral = new javax.swing.JButton();
        buttonHappy = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        buttonHome = new javax.swing.JButton();
        buttonDiary = new javax.swing.JButton();
        buttonClinic = new javax.swing.JButton();
        buttonForum = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        buttonLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(720, 60));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(13, 76, 115));
        jPanel1.setMaximumSize(new java.awt.Dimension(394, 852));
        jPanel1.setMinimumSize(new java.awt.Dimension(394, 852));
        jPanel1.setPreferredSize(new java.awt.Dimension(394, 852));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/healy-logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 6, -1, -1));

        buttonSad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonEmoSad.png"))); // NOI18N
        buttonSad.setContentAreaFilled(false);
        jPanel1.add(buttonSad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 100, 140));

        buttonNeutral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonEmoNeutral.png"))); // NOI18N
        buttonNeutral.setContentAreaFilled(false);
        jPanel1.add(buttonNeutral, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 349, 120, 140));

        buttonHappy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonEmoHappy.png"))); // NOI18N
        buttonHappy.setContentAreaFilled(false);
        jPanel1.add(buttonHappy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 352, 110, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/doctor.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 211, 153));
        jLabel8.setText("WELCOME,");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(242, 211, 153));
        labelUsername.setText("USERNAME!");
        jPanel1.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 360, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("How are you");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("feeling today?");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/backgroundEmotion.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 400, 180));

        footer.setBackground(new java.awt.Color(13, 76, 115));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonHome.setBackground(new java.awt.Color(144, 224, 239));
        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonHome-select.png"))); // NOI18N
        buttonHome.setBorder(null);
        buttonHome.setBorderPainted(false);
        buttonHome.setContentAreaFilled(false);
        buttonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHomeMouseClicked(evt);
            }
        });
        buttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHomeActionPerformed(evt);
            }
        });
        footer.add(buttonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        buttonDiary.setBackground(new java.awt.Color(144, 224, 239));
        buttonDiary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonDiary.png"))); // NOI18N
        buttonDiary.setBorder(null);
        buttonDiary.setBorderPainted(false);
        buttonDiary.setContentAreaFilled(false);
        buttonDiary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDiaryMouseClicked(evt);
            }
        });
        footer.add(buttonDiary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 80, -1));

        buttonClinic.setBackground(new java.awt.Color(144, 224, 239));
        buttonClinic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonClinic.png"))); // NOI18N
        buttonClinic.setBorder(null);
        buttonClinic.setBorderPainted(false);
        buttonClinic.setContentAreaFilled(false);
        buttonClinic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClinic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClinicMouseClicked(evt);
            }
        });
        buttonClinic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClinicActionPerformed(evt);
            }
        });
        footer.add(buttonClinic, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 80, -1));

        buttonForum.setBackground(new java.awt.Color(144, 224, 239));
        buttonForum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonForum.png"))); // NOI18N
        buttonForum.setBorder(null);
        buttonForum.setBorderPainted(false);
        buttonForum.setContentAreaFilled(false);
        buttonForum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonForum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonForumMouseClicked(evt);
            }
        });
        footer.add(buttonForum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 80, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/footerWide.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        footer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, -1));

        jPanel1.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 730, 400, 120));

        buttonLogOut.setBackground(new java.awt.Color(13, 76, 115));
        buttonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonLogOut.png"))); // NOI18N
        buttonLogOut.setBorder(null);
        buttonLogOut.setBorderPainted(false);
        buttonLogOut.setContentAreaFilled(false);
        buttonLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLogOutMouseClicked(evt);
            }
        });
        jPanel1.add(buttonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonHomeActionPerformed

    private void buttonClinicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClinicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClinicActionPerformed

    private void buttonLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogOutMouseClicked
        Index logout = new Index();
        logout.show();
        dispose();
    }//GEN-LAST:event_buttonLogOutMouseClicked

    private void buttonClinicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClinicMouseClicked
        ClinicMenuCl clinic = new ClinicMenuCl(id);
        clinic.show();
        dispose();
    }//GEN-LAST:event_buttonClinicMouseClicked

    private void buttonForumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonForumMouseClicked
        ForumMenuCl forum = new ForumMenuCl(id);
        forum.show();
        dispose();
    }//GEN-LAST:event_buttonForumMouseClicked

    private void buttonDiaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDiaryMouseClicked
        DiaryMenuCl diaryMenu = new DiaryMenuCl(id);
        diaryMenu.show();
        dispose();
    }//GEN-LAST:event_buttonDiaryMouseClicked

    private void buttonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseClicked
        HomeCl homeCl = new HomeCl(id);
        homeCl.show();
        dispose();
    }//GEN-LAST:event_buttonHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeCl(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClinic;
    private javax.swing.JButton buttonDiary;
    private javax.swing.JButton buttonForum;
    private javax.swing.JButton buttonHappy;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JButton buttonNeutral;
    private javax.swing.JButton buttonSad;
    private javax.swing.JPanel footer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelUsername;
    // End of variables declaration//GEN-END:variables
}
