/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package healy;

/**
 *
 * @author an6el
 */
public class LoginDoctor extends javax.swing.JFrame {
    private static int id;
    
    /**
     * Creates new form login
     */
    public LoginDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupEmailErr = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        popupPassErr = new javax.swing.JDialog();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        popupContinue = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonContinue = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        containerHead = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        containerBody = new javax.swing.JPanel();
        inputEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        buttonLogin = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        popupEmailErr.setBackground(new java.awt.Color(13, 76, 115));
        popupEmailErr.setLocation(new java.awt.Point(735, 320));
        popupEmailErr.setMinimumSize(new java.awt.Dimension(380, 200));
        popupEmailErr.setResizable(false);
        popupEmailErr.setSize(new java.awt.Dimension(380, 200));
        popupEmailErr.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(13, 76, 115));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EMAIL NOT FOUND");
        jLabel3.setMaximumSize(new java.awt.Dimension(380, 300));
        jLabel3.setMinimumSize(new java.awt.Dimension(380, 300));
        jLabel3.setPreferredSize(new java.awt.Dimension(380, 300));
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 170));

        popupEmailErr.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 200));

        popupPassErr.setBackground(new java.awt.Color(13, 76, 115));
        popupPassErr.setLocation(new java.awt.Point(735, 320));
        popupPassErr.setMaximumSize(new java.awt.Dimension(380, 200));
        popupPassErr.setMinimumSize(new java.awt.Dimension(380, 200));
        popupPassErr.setResizable(false);
        popupPassErr.setSize(new java.awt.Dimension(380, 200));
        popupPassErr.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(13, 76, 115));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PASSWORD INCORRECT");
        jLabel7.setMaximumSize(new java.awt.Dimension(380, 300));
        jLabel7.setMinimumSize(new java.awt.Dimension(380, 300));
        jLabel7.setPreferredSize(new java.awt.Dimension(380, 300));
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 180));

        popupPassErr.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 200));

        popupContinue.setBackground(new java.awt.Color(13, 76, 115));
        popupContinue.setLocation(new java.awt.Point(735, 320));
        popupContinue.setMaximumSize(new java.awt.Dimension(380, 250));
        popupContinue.setMinimumSize(new java.awt.Dimension(380, 250));
        popupContinue.setResizable(false);
        popupContinue.setSize(new java.awt.Dimension(380, 250));
        popupContinue.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(13, 76, 115));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SUCCESSFULLY");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 380, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(144, 224, 239));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Logged In");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, 40));

        buttonContinue.setBackground(new java.awt.Color(13, 76, 115));
        buttonContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonContinue.png"))); // NOI18N
        buttonContinue.setBorder(null);
        buttonContinue.setBorderPainted(false);
        buttonContinue.setContentAreaFilled(false);
        buttonContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonContinueMouseClicked(evt);
            }
        });
        buttonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContinueActionPerformed(evt);
            }
        });
        jPanel5.add(buttonContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 260, 60));

        popupContinue.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 250));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(13, 76, 115));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(720, 60));
        setMinimumSize(new java.awt.Dimension(408, 876));
        setResizable(false);
        setSize(new java.awt.Dimension(408, 876));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(13, 76, 115));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(394, 852));
        jPanel3.setMinimumSize(new java.awt.Dimension(394, 852));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(394, 852));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        containerHead.setBackground(new java.awt.Color(13, 76, 115));
        containerHead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/headerHello.png"))); // NOI18N
        containerHead.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 410, 70));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/headerLogin.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        containerHead.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 410, 50));

        jPanel3.add(containerHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 150));

        containerBody.setBackground(new java.awt.Color(13, 76, 115));
        containerBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputEmail.setBorder(null);
        containerBody.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 260, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/inputEmail.png"))); // NOI18N
        containerBody.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 340, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email Address");
        containerBody.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        inputPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputPassword.setBorder(null);
        inputPassword.setDragEnabled(true);
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        containerBody.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 260, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        containerBody.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/inputPassword.png"))); // NOI18N
        containerBody.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 340, 60));

        jButton1.setBackground(new java.awt.Color(13, 76, 115));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 211, 153));
        jButton1.setText("Forgot Password?");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        containerBody.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 180, -1));

        jPanel3.add(containerBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 410, 300));

        jPanel2.setBackground(new java.awt.Color(13, 76, 115));

        buttonLogin.setBackground(new java.awt.Color(13, 76, 115));
        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonLogin.png"))); // NOI18N
        buttonLogin.setBorder(null);
        buttonLogin.setBorderPainted(false);
        buttonLogin.setContentAreaFilled(false);
        buttonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoginMouseClicked(evt);
            }
        });
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 410, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/OR split.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 410, 40));

        jButton5.setBackground(new java.awt.Color(13, 76, 115));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonApple.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 330, 60));

        jButton2.setBackground(new java.awt.Color(13, 76, 115));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonGoogle.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 330, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseClicked
        String email = inputEmail.getText();
        String password = inputPassword.getText();
        Doctor counselor = new Doctor();
        int result = counselor.login(email, password);
        this.id = counselor.id;
        switch(result){
            case -1:
                popupEmailErr.show();
                popupPassErr.dispose();
                popupContinue.dispose();
                break;
            
            case 0:
                popupEmailErr.dispose();
                popupPassErr.show();
                popupContinue.dispose();
                break;
                
            case 1:
                popupEmailErr.dispose();
                popupPassErr.dispose();
                popupContinue.show();
                break;  
                
        }
        
    }//GEN-LAST:event_buttonLoginMouseClicked

    private void buttonContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonContinueMouseClicked
        MenuDoc menuDoc = new MenuDoc(id);
        menuDoc.show();
        popupContinue.dispose();
        dispose();
    }//GEN-LAST:event_buttonContinueMouseClicked

    private void buttonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContinueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonContinue;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JPanel containerBody;
    private javax.swing.JPanel containerHead;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JDialog popupContinue;
    private javax.swing.JDialog popupEmailErr;
    private javax.swing.JDialog popupPassErr;
    // End of variables declaration//GEN-END:variables
}
