package healy;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JPanel;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class ThreadShowCl extends javax.swing.JFrame {
    private static int id, idThread;
    
    
    /**
     * Creates new form ThreadShowCl
     */
    public ThreadShowCl(int id, int idThread) {
        initComponents();
        this.id = id;
        this.idThread = idThread;
        
        Thread thread = new Thread();
        threadTitle.setText(thread.getTitle(idThread));
        threadEntry.setText(thread.getEntry(idThread));
        threadGiver.setText(thread.getUsername(idThread));
        
        JPanel[] commentBox = new JPanel[3];
        JLabel[] commentGiver = new JLabel[3];
        JLabel[] commentEntry = new JLabel[3];
        panelComment.setSize(400, 230);
        int i = 1, y = 10;
        
        try {
            String url = "jdbc:mysql://localhost:3306/healyDB?zeroDateTimeBehavior=CONVERT_TO_NULL";
            String user = "root";
            String pass = "pass";

            Connection con = DriverManager.getConnection(url, user, pass);
            System.out.println("[debug]BEFORE CHECKING");
            Statement stmt = con.createStatement();
            String Query = "SELECT comments.comment_entry, users.nama_user FROM comments INNER JOIN users ON comments.user_id = users.user_id WHERE forum_id = '"+idThread+"'";
            ResultSet rs = stmt.executeQuery(Query);
            System.out.println("[debug]AFTER CHECKING");

            while (rs.next()) {
                commentBox[i] = new JPanel();
                commentBox[i].setBounds(20, y, 360, 75);
                commentBox[i].setBackground(new Color(0, 119, 182));
                commentBox[i].setVisible(true);
                System.out.println("[debug]AFTER Comment box");
                
                
                commentGiver[i] = new JLabel();
                commentGiver[i].setBounds(30, y+5, 340, 25);
                commentGiver[i].setForeground(Color.WHITE);
                commentGiver[i].setFont(new Font("Segoe UI", 1, 14));
                String commentUserName = rs.getString("nama_user");
                commentGiver[i].setText(commentUserName);
                commentGiver[i].setVisible(true);
                System.out.println("[debug]AFTER Comment Giver");
                
                
                commentEntry[i] = new JLabel();
                commentEntry[i].setBounds(30, y+30, 340, 25);
                commentEntry[i].setForeground(Color.WHITE);
                commentEntry[i].setFont(new Font("Segoe UI", 0, 14));
                commentEntry[i].setText(rs.getString("comment_entry"));
                commentEntry[i].setVisible(true);
                
                System.out.println("[debug]PRINT" + i);
                System.out.println(commentUserName);
                System.out.println(rs.getString("comment_entry"));

                panelComment.add(commentGiver[i]);
                panelComment.add(commentEntry[i]);
                panelComment.add(commentBox[i]);
                panelComment.setVisible(true);

                i += 1;
                y += 85;
            }

        } catch (SQLException ex) {
            System.out.println("[debug]ERROR PRINT");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelThread = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        threadEntry = new javax.swing.JTextArea();
        threadTitle = new javax.swing.JLabel();
        threadGiver = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelComment = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        buttonHome = new javax.swing.JButton();
        buttonDiary = new javax.swing.JButton();
        buttonClinic = new javax.swing.JButton();
        buttonForum = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        panelInput = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        inputComment = new javax.swing.JTextField();
        buttonSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(720, 60));
        setMinimumSize(new java.awt.Dimension(396, 852));
        setResizable(false);
        setSize(new java.awt.Dimension(396, 852));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(13, 76, 115));
        header.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/healy-logo.png"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setMaximumSize(new java.awt.Dimension(232, 188));
        jLabel3.setMinimumSize(new java.awt.Dimension(232, 188));
        jLabel3.setPreferredSize(new java.awt.Dimension(232, 188));
        header.add(jLabel3);
        jLabel3.setBounds(200, 10, 200, 120);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/headerForum.png"))); // NOI18N
        header.add(jLabel5);
        jLabel5.setBounds(0, -10, 190, 140);

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 140));

        panelThread.setBackground(new java.awt.Color(13, 76, 115));
        panelThread.setAutoscrolls(true);
        panelThread.setPreferredSize(new java.awt.Dimension(400, 500));
        panelThread.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 119, 182));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        threadEntry.setEditable(false);
        threadEntry.setBackground(new java.awt.Color(0, 119, 182));
        threadEntry.setColumns(20);
        threadEntry.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        threadEntry.setForeground(new java.awt.Color(255, 255, 255));
        threadEntry.setRows(5);
        threadEntry.setText("Label panel");
        threadEntry.setBorder(null);
        threadEntry.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(threadEntry);

        panelThread.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 340, 120));

        threadTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        threadTitle.setForeground(new java.awt.Color(255, 255, 255));
        threadTitle.setText("jLabel2");
        panelThread.add(threadTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, 30));

        threadGiver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        threadGiver.setForeground(new java.awt.Color(255, 255, 255));
        threadGiver.setText("jLabel2");
        panelThread.add(threadGiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 280, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/backgroundThread.png"))); // NOI18N
        panelThread.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 240));

        getContentPane().add(panelThread, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 400, 250));

        panelComment.setBackground(new java.awt.Color(13, 76, 115));
        panelComment.setAutoscrolls(true);
        panelComment.setPreferredSize(new java.awt.Dimension(400, 500));

        javax.swing.GroupLayout panelCommentLayout = new javax.swing.GroupLayout(panelComment);
        panelComment.setLayout(panelCommentLayout);
        panelCommentLayout.setHorizontalGroup(
            panelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelCommentLayout.setVerticalGroup(
            panelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(panelComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 400, 230));

        footer.setBackground(new java.awt.Color(13, 76, 115));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonHome.setBackground(new java.awt.Color(144, 224, 239));
        buttonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonHome.png"))); // NOI18N
        buttonHome.setBorder(null);
        buttonHome.setBorderPainted(false);
        buttonHome.setContentAreaFilled(false);
        buttonHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHomeMouseClicked(evt);
            }
        });
        footer.add(buttonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        buttonDiary.setBackground(new java.awt.Color(144, 224, 239));
        buttonDiary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonDiary.png"))); // NOI18N
        buttonDiary.setBorder(null);
        buttonDiary.setBorderPainted(false);
        buttonDiary.setContentAreaFilled(false);
        buttonDiary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDiaryMouseClicked(evt);
            }
        });
        footer.add(buttonDiary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 80, -1));

        buttonClinic.setBackground(new java.awt.Color(144, 224, 239));
        buttonClinic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonClinic.png"))); // NOI18N
        buttonClinic.setBorder(null);
        buttonClinic.setBorderPainted(false);
        buttonClinic.setContentAreaFilled(false);
        buttonClinic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonClinic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonClinicMouseClicked(evt);
            }
        });
        footer.add(buttonClinic, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 80, -1));

        buttonForum.setBackground(new java.awt.Color(144, 224, 239));
        buttonForum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonForum-select.png"))); // NOI18N
        buttonForum.setBorder(null);
        buttonForum.setBorderPainted(false);
        buttonForum.setContentAreaFilled(false);
        buttonForum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonForum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonForumMouseClicked(evt);
            }
        });
        footer.add(buttonForum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 80, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/footerWide.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        footer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 420, -1));

        getContentPane().add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 400, 120));

        panelInput.setBackground(new java.awt.Color(13, 76, 115));

        jPanel3.setBackground(new java.awt.Color(0, 119, 182));
        jPanel3.setPreferredSize(new java.awt.Dimension(360, 100));

        inputComment.setBackground(new java.awt.Color(0, 119, 182));
        inputComment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputComment.setForeground(new java.awt.Color(255, 255, 255));
        inputComment.setText("input comment...");
        inputComment.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inputComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCommentActionPerformed(evt);
            }
        });

        buttonSend.setBackground(new java.awt.Color(0, 119, 182));
        buttonSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/healy/asset/buttonSendSmall.png"))); // NOI18N
        buttonSend.setBorder(null);
        buttonSend.setContentAreaFilled(false);
        buttonSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSend.setFocusPainted(false);
        buttonSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSendMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputComment, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSend)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputComment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(panelInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 400, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseClicked
        HomeCl homeCl = new HomeCl(id);
        homeCl.show();
        dispose();
    }//GEN-LAST:event_buttonHomeMouseClicked

    private void buttonDiaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDiaryMouseClicked
        DiaryMenuCl diaryMenu = new DiaryMenuCl(id);
        diaryMenu.show();
        dispose();
    }//GEN-LAST:event_buttonDiaryMouseClicked

    private void buttonClinicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClinicMouseClicked
        ClinicMenuCl clinic = new ClinicMenuCl(id);
        clinic.show();
        dispose();
    }//GEN-LAST:event_buttonClinicMouseClicked

    private void buttonForumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonForumMouseClicked
        ForumMenuCl forum = new ForumMenuCl(id);
        forum.show();
        dispose();
    }//GEN-LAST:event_buttonForumMouseClicked

    private void inputCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCommentActionPerformed

    private void buttonSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSendMouseClicked
        String entry = inputComment.getText();
        
        Comment comment = new Comment();
        int result = comment.insert(id, idThread, entry);
        if(result == 1){
            System.out.println("COMMENT ADDED");
            ThreadShowCl thread = new ThreadShowCl(id, idThread);
            thread.show();
            dispose();
        }else System.out.println("COMMENT ERROR");
    }//GEN-LAST:event_buttonSendMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreadShowCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreadShowCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreadShowCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreadShowCl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreadShowCl(id, idThread).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClinic;
    private javax.swing.JButton buttonDiary;
    private javax.swing.JButton buttonForum;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonSend;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JTextField inputComment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelComment;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelThread;
    private javax.swing.JTextArea threadEntry;
    private javax.swing.JLabel threadGiver;
    private javax.swing.JLabel threadTitle;
    // End of variables declaration//GEN-END:variables
}
